version: '3'
services:
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.5.2
    user: root
    volumes:
      - $PWD/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat -e -E output.elasticsearch.hosts=["YOUR_IP:9200"] -strict.perms=false

